[project]
name = "MADS-DAV"
version = "0.1.0"
description = "Code for the Master of Applied Data Science course Data Analysis and Visualization"
authors = [
    {name = "Raoul Grouls", email = "Raoul.Grouls@han.nl"},
]
dependencies = [
    "seaborn>=0.13.1",
    "numpy>=1.26.3",
    "jupyter>=1.0.0",
    "pydantic>=2.5.3",
    "pandas>=2.2.0",
    "loguru>=0.7.2",
    "pyarrow>=15.0.0",
    "plotly>=5.18.0",
    "click>=8.1.7",
    "mads-datasets>=0.3.10",
    "scikit-learn>=1.4.0",
]

requires-python = ">=3.10,<3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
lint = [
    "black>=23.12.1",
    "isort>=5.13.2",
    "ruff>=0.1.14",
    "mypy>=1.8.0",
]

[tool.mypy]
allow_redefinition = true
ignore_missing_imports = true
pretty = true
